### ISSUE TITLE
Getting error with running hello_world_rust.wasm

### ISSUE THREAD

**Issue by allthingssecurity** [wapc/wasmtime-provider#11]
I am running the following code 
fn runs_wapc_guest() -> anyhow::Result<()> {
    let buf = read("/home/ubuntu/testwasm/hello_world_rust.wasm".to_string())?;

    let engine = wasmtime_provider::WasmtimeEngineProvider::new(&buf, None);
    let guest = WapcHost::new(Box::new(engine), move |_a, _b, _c, _d, _e| Ok(vec![]))?;
println!("before invoking wasm");
    let callresult = guest.call("sayHello", &serialize("foo").unwrap()).unwrap();

I have used the rust wasm example and get the following error

before invoking wasm
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(GuestCallFailure("Guest call failed: Failed to de-serialize: invalid type: string \"foo\", expected struct SayHelloArgs"))', src/main.rs:27:73

**Comment by allthingssecurity** [comment]
I tried to print the serialized array in working code with javascript(nodejs invoking same wasm)
This is the serialized array Uint8Array(10) [
  129, 164, 110,  97,
  109, 101, 163, 102,
  111, 111
]
For Rust based example I get something different
[174, 34, 123, 110, 97, 109, 101, 58, 39, 102, 111, 111, 39, 125, 34]

Once I tried passing the js generate array the code worked. Looks like some issue with the way I am doing serialization here.

**Comment by allthingssecurity** [comment]
Finally I serialized it using serd_json and msgpack in serdconv to get this to work.

**Comment by autodidaddict** [comment]
glad you got it working. The clue was in the error message ` expected struct SayHelloArgs")` , you can't send a string "foo", you had to send a serialized version of `SayHelloArgs`
