### ISSUE TITLE
Upgrade to wasmtime 0.22

### ISSUE THREAD

**Issue by theduke** [wapc/wasmtime-provider#5]
Wasmtime is on 0.22 now.

I tried an upgrade, but there appear to have been quite a few breaking changes.

I'll see if I find the time to do it.

**Comment by brooksmtownsend** [comment]
Refreshing this issue, there was recently an issue closed on the wasmtime repo that includes aarch64 compilation support as a platform: https://github.com/bytecodealliance/wasmtime/issues/339#issuecomment-629849051. We should update fully to wasmtime v0.22.1 to support this additional target.

**Comment by pkedy** [comment]
Closing this issue because it was at least updated to 0.24.0 in #7.
